" My work .vimrc configuration
" A bit obsolete, since I switched to VSCode, but still relevant!

" This is the basic vimrc that I will use for whenever vim is available
" Note that in order to use this, we will need to install pathogen  as well as get the iceberg them

syntax on
filetype plugin indent on
colorscheme iceberg

set autoindent
set expandtab
set number
set shiftwidth=2
set softtabstop=2
set backup
set noswapfile
set noundofile
set backspace=indent,eol,start
set spell spelllang=en_us
set re=2

" Word Wrapping
set wrap
set linebreak
set nolist  " list disables linebreak
set textwidth=0
set wrapmargin=0
set formatoptions-=t
set backupdir=~/.vim/backup

"Remapping Arrow keys for usage in insert
inoremap <Esc>A <up>
inoremap <Esc>B <down>
inoremap <Esc>C <right>
inoremap <Esc>D <left>

" Smooth Scrolling
noremap <silent> <c-k> :call smooth_scroll#up(&scroll, 0, 1)<CR>
noremap <silent> <c-j> :call smooth_scroll#down(&scroll, 0, 1)<CR>
